### ISSUE TITLE
Track/Album playable but not downloadable.

### ISSUE THREAD

**Issue by geoplayx** [glomatico/spotify-aac-downloader#5]
Some tracks/albums can be played but i cannot download it.

https://open.spotify.com/album/27zEODZr1lHmrtaapO6r8r?si=A0MVG0F9TsiU06O4Tyngjw

Many tracks are not downloadable in this playlist but it can be played on my account.

https://open.spotify.com/playlist/5JOn3LSfpbCrOQ7azB4S6C?si=uqohs1GSTn6AID_da5pYZA

**Comment by futaride** [comment]
Hello, using spotify-aac-downloader followed by spotify link works. Using spotify-aac-downloader url followed by spotify link does not. Sorry for wording this weird, English is difficult for me.

**Comment by glomatico** [comment]
Fixed.

**Comment by geoplayx** [comment]
Not all, try this link https://open.spotify.com/album/0WzPaJFRUSZXW9RdYsgr8v?si=CSwYsqFgTuOHHz34QdZBTg

**Comment by glomatico** [comment]
Try updating your pybase62 package
```
pip install pybase62 --upgrade
```

**Comment by geoplayx** [comment]
“Requirement already satisfied: pybase62 in /usr/local/lib/python3.10/dist-packages (1.0.0)”

And still cannot download that album. It’s playable in my account (premium).

**Comment by glomatico** [comment]
Send the output with `--print-exceptions` argument

**Comment by geoplayx** [comment]
Downloading "Way Back - Recorded at Spotify Studios NYC" (track 1/2 from URL 1/1)
Failed to download "Way Back - Recorded at Spotify Studios NYC" (track 1/2 from URL 1/1)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/spotify_aac_downloader/__init__.py", line 124, in main
    tags = dl.get_tags(metadata, unsynced_lyrics)
  File "/usr/local/lib/python3.10/dist-packages/spotify_aac_downloader/spotify_aac_downloader.py", line 166, in get_tags
    copyright = next(i['text'] for i in album['copyrights'] if i['type'] == 'P')
StopIteration
Downloading "Waterfalls - Recorded at Spotify Studios NYC" (track 2/2 from URL 1/1)
Failed to download "Waterfalls - Recorded at Spotify Studios NYC" (track 2/2 from URL 1/1)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/spotify_aac_downloader/__init__.py", line 124, in main
    tags = dl.get_tags(metadata, unsynced_lyrics)
  File "/usr/local/lib/python3.10/dist-packages/spotify_aac_downloader/spotify_aac_downloader.py", line 166, in get_tags
    copyright = next(i['text'] for i in album['copyrights'] if i['type'] == 'P')
StopIteration
Done (2 error(s))

**Comment by glomatico** [comment]
> Downloading "Way Back - Recorded at Spotify Studios NYC" (track 1/2 from URL 1/1) Failed to download "Way Back - Recorded at Spotify Studios NYC" (track 1/2 from URL 1/1) Traceback (most recent call last): File "/usr/local/lib/python3.10/dist-packages/spotify_aac_downloader/**init**.py", line 124, in main tags = dl.get_tags(metadata, unsynced_lyrics) File "/usr/local/lib/python3.10/dist-packages/spotify_aac_downloader/spotify_aac_downloader.py", line 166, in get_tags copyright = next(i['text'] for i in album['copyrights'] if i['type'] == 'P') StopIteration Downloading "Waterfalls - Recorded at Spotify Studios NYC" (track 2/2 from URL 1/1) Failed to download "Waterfalls - Recorded at Spotify Studios NYC" (track 2/2 from URL 1/1) Traceback (most recent call last): File "/usr/local/lib/python3.10/dist-packages/spotify_aac_downloader/**init**.py", line 124, in main tags = dl.get_tags(metadata, unsynced_lyrics) File "/usr/local/lib/python3.10/dist-packages/spotify_aac_downloader/spotify_aac_downloader.py", line 166, in get_tags copyright = next(i['text'] for i in album['copyrights'] if i['type'] == 'P') StopIteration Done (2 error(s))

Should be fully fixed on the new version.
